export const GET_SEMESTER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/semester"
export const POST_SEMESTER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/semester"
export const GET_SINGLE_SEMESTER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/semester/"
export const PUT_SEMESTER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/semester/"
export const DEL_SEMESTER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/semester/"

export const GET_SECTION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/section"
export const POST_SECTION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/section"
export const GET_SINGLE_SECTION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/section/"
export const PUT_SECTION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/section/"
export const DEL_SECTION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/section/"

export const GET_DEPARTMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/department"
export const POST_DEPARTMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/department"
export const GET_SINGLE_DEPARTMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/department/"
export const PUT_DEPARTMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/department/"
export const DEL_DEPARTMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/department/"

export const GET_TEACHER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/teacher"
export const POST_TEACHER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/teacher"
export const GET_SINGLE_TEACHER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/teacher/"
export const PUT_TEACHER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/teacher/"
export const DEL_TEACHER = import.meta.env.VITE_API_SERVER_URL + "/api/v1/academic/teacher/"

export const GET_PAYMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/payment"
export const POST_PAYMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/payment"
export const PUT_PAYMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/payment/"
export const DEL_PAYMENT = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/payment/"

export const GET_ADMISSION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/admission"
export const POST_ADMISSION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/admission"
export const GET_SINGLE_ADMISSION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/admission/"
export const PUT_ADMISSION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/admission/"
export const DEL_ADMISSION = import.meta.env.VITE_API_SERVER_URL + "/api/v1/student/admission/"